@token = 

### Get all

GET http://localhost:3000/api/v1/users HTTP/1.1
Authorization: Barer {{token}}

### Get one by id

GET http://localhost:3000/api/v1/users/1 HTTP/1.1

### Update profile

PUT http://localhost:3000/api/v1/users/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Alexander",
  "lastname": "Dowee"
}

### Ban/Unban user

PUT http://localhost:3000/api/v1/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Barer {{token}}

{
  "status": "BANNED"
}

### Update password

PUT http://localhost:3000/api/v1/users/1 HTTP/1.1
Content-Type: application/json

{
  "password": "password-changed"
}

### Create user

POST http://localhost:3000/api/v1/users/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Alex",
  "lastname": "Doe",
  "email": "alex.doe@mail.com",
  "password": "6287dba664e931cb46c9d0a0"
}

### Login user

# POST http://localhost:3000/api/v1/users/login HTTP/1.1
# Content-Type: application/json

# {
#   "email": "alex.doe@mail.com",
#   "password": "6287dba664e931cb46c9d0a0"
# }

### Delete one

DELETE http://localhost:3000/api/v1/users/1 HTTP/1.1
