version: "3"
services:
  api:
    build: ./api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=
      - JWT_SECRET=super-secret-phrase
      - PORT=5000
      # - NODE_ENV=production
  client:
    build: 
      context: ./client
    restart: unless-stopped
    ports:
      - "3000:3000"
    # environment: # these are not working
    #   - REACT_APP_GOOGLE_CLIENT_ID=
    #   - REACT_APP_API_BASE_URL=http://api/api/v1
    #   - NODE_ENV=production
    depends_on:
      - api