@token = 

### Get all

GET http://localhost:5000/api/v1/users HTTP/1.1

###

GET http://localhost:5000/api/v1/users/628fb22732c84c42115c474c HTTP/1.1

### Update profile

PUT http://localhost:5000/api/v1/users/628fb22732c84c42115c474c/profile HTTP/1.1
Content-Type: application/json

{
  "name": "Alex",
  "lastname": "Doe",
}

### Ban/Unban user

PUT http://localhost:5000/api/v1/users/6287dba664e931cb46c9d0a0/status HTTP/1.1
Content-Type: application/json
Authorization: Barer {{token}}

{
  "status": "BANNED"
}

### Update password

PUT http://localhost:5000/api/v1/users/6287dba664e931cb46c9d0a0/password HTTP/1.1
Content-Type: application/json

{
  "oldPassword": "password",
  "newPassword": "password-changed"
}

### Forgot password request

PUT http://localhost:5000/api/v1/users/password-reset HTTP/1.1
Content-Type: application/json

{
  "email": "alex.doe@mail.com"
}

### Update password with token

PUT http://localhost:5000/api/v1/users/password-reset HTTP/1.1
Content-Type: application/json

{
  "resetToken": "ca8e607bcca3238a5df6c40153615723932b0517beba3105410094d04d67447adf7de7fbe68a92bfa8b1f5040abb86dc559e714d685b5f723ad3f3d7e9028aba",
  "newPassword": "password-reseted"
}

### Create user

POST http://localhost:5000/api/v1/users/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Alex",
  "lastname": "Doe",
  "email": "alex.doe@mail.com",
  "password": "6287dba664e931cb46c9d0a0",
  "role": "ADMIN"
}

### Login user

POST http://localhost:5000/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "alex.doe@mail.com",
  "password": "6287dba664e931cb46c9d0a0"
}

### Delete one

DELETE http://localhost:5000/api/v1/users/628ca93d15e5da4157847c5a HTTP/1.1
