name: API CI/CD workflow

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "api/**"
      - ".github/workflows/**"

jobs:
  ci:
    name: Setup, Test, and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Pwd
        run: pwd

      - name: Git log
        run: git log --oneline

      - name: Get yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-api-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-api-modules-
            ${{ runner.os }}-

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      # - name: Test
      #   run: yarn test

      - name: Build
        run: yarn build

      - name: Return to base dir
        run: cd ..

  cd:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Ls
        run: ls -a
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "peaceful-canyonlands-26888"
          appdir: "api"
          # justlogin: true
      # - run: heroku auth:whoami
