name: API CI/CD workflow

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "api/**"
      - ".github/workflows/**"

jobs:
  ci:
    name: Setup, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout folder
        uses: Bhacaz/checkout-files@v2
        with:
          files: api

      - name: Move folder contents to root
        run: |
          shopt -s dotglob
          mv -v api/* .

      - name: Remove former folder
        run: rm -d api

      - name: Get yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
            ${{ runner.os }}-

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      # - name: Test
      #   run: yarn test

      - name: Build
        run: yarn build

  cd:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Git init
        run: |
          git init
          git config user.email ${{ secrets.HEROKU_EMAIL }}
          git config user.name ${{ secrets.NAME }}
          git add .
          git commit -m "First commit"
          git branch -m main

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "peaceful-canyonlands-26888"
          appdir: "."
          # justlogin: true
      # - run: heroku auth:whoami
