name: API CI/CD workflow

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/api.*"

jobs:
  build:
    name: Build and Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup yarn cache
        working-directory: api
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-api-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-api-modules-
            ${{ runner.os }}-

      - name: Install packages
        working-directory: api
        run: yarn install --frozen-lockfile

      - name: Lint
        working-directory: api
        run: yarn lint

      # - name: Test
      #   working-directory: api
      #   run: yarn test

      - name: Build
        working-directory: api
        run: yarn build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "peaceful-canyonlands-26888"
          appdir: "api"
          # justlogin: true
      # - run: heroku auth:whoami
