name: Client CI/CD workflow

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/client.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use only client folder
        run: |
          find . -type f \! -path "./client*" -delete
          find . -type d \! -path "./client*" \! -path "./.git*" -delete
          mv client/* .
          rm -r client

      - name: Get yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-client-modules-${{ hashFiles('client/yarn-lock') }}
          restore-keys: |
            ${{ runner.os }}-client-modules-
            ${{ runner.os }}-

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      # - name: Build
      #   run: yarn build

      - name: Build with Netlify CLI
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify build

      - if: ${{ github.event_name == 'pull_request' }}
        name: Deploy to Netlify (draft)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --dir build --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --message=${{ github.event.head_commit.message }}

      - if: ${{ github.event_name == 'push' }}
        name: Deploy to Netlify (production)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --dir build --prod --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --message=${{ github.event.head_commit.message }}
